create table if not exists public.community_member_snapshots(
  id bigint generated by default as identity primary key,
  community_id uuid not null references public.communities(id) on delete cascade,
  member_count integer not null check (member_count>=0),
  observed_at timestamptz not null default now(),
  observed_on date not null,
  source text not null default 'campfire-event-club',
  created_at timestamptz not null default now(),
  unique(community_id,observed_on)
);

create index if not exists community_member_snapshots_community_observed_idx
  on public.community_member_snapshots(community_id,observed_on desc);

create table if not exists public.meetup_metric_snapshots(
  id bigint generated by default as identity primary key,
  meetup_id uuid not null references public.meetups(id) on delete cascade,
  community_id uuid not null references public.communities(id) on delete cascade,
  rsvp_count integer check (rsvp_count is null or rsvp_count>=0),
  checkin_count integer check (checkin_count is null or checkin_count>=0),
  observed_at timestamptz not null,
  source text not null default 'campfire-public-map',
  created_at timestamptz not null default now(),
  unique(meetup_id,observed_at)
);

create index if not exists meetup_metric_snapshots_meetup_observed_idx
  on public.meetup_metric_snapshots(meetup_id,observed_at desc);
create index if not exists meetup_metric_snapshots_community_observed_idx
  on public.meetup_metric_snapshots(community_id,observed_at desc);
create index if not exists meetup_metric_snapshots_observed_idx
  on public.meetup_metric_snapshots(observed_at);

create table if not exists public.community_member_sync_state(
  id smallint primary key default 1 check(id=1),
  snapshot_date date,
  next_offset integer not null default 0 check(next_offset>=0),
  failed_community_ids uuid[] not null default '{}'::uuid[],
  started_at timestamptz,
  finished_at timestamptz,
  updated_at timestamptz not null default now(),
  last_error text
);

insert into public.community_member_sync_state(id)
values(1)
on conflict(id) do nothing;

alter table public.community_member_snapshots enable row level security;
alter table public.meetup_metric_snapshots enable row level security;
alter table public.community_member_sync_state enable row level security;

drop policy if exists "read allowed community member snapshots" on public.community_member_snapshots;
create policy "read allowed community member snapshots"
on public.community_member_snapshots
for select
to authenticated
using(
  private.is_admin()
  or exists(
    select 1
    from public.community_memberships m
    where m.community_id=community_member_snapshots.community_id
      and m.user_id=(select auth.uid())
  )
);

drop policy if exists "read allowed meetup metric snapshots" on public.meetup_metric_snapshots;
create policy "read allowed meetup metric snapshots"
on public.meetup_metric_snapshots
for select
to authenticated
using(
  private.is_admin()
  or exists(
    select 1
    from public.community_memberships m
    where m.community_id=meetup_metric_snapshots.community_id
      and m.user_id=(select auth.uid())
  )
);

drop policy if exists "community member sync state admin read" on public.community_member_sync_state;
create policy "community member sync state admin read"
on public.community_member_sync_state
for select
to authenticated
using(private.is_admin());

revoke all on public.community_member_snapshots from anon,authenticated;
revoke all on public.meetup_metric_snapshots from anon,authenticated;
revoke all on public.community_member_sync_state from anon,authenticated;
grant select on public.community_member_snapshots to authenticated;
grant select on public.meetup_metric_snapshots to authenticated;
grant select on public.community_member_sync_state to authenticated;
