insert into public.watch_terms (phrase,category,severity,flag_code,regex,negative_pattern,enabled,rule_version) values
('プライベート','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('プライベート開催','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('非公開','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('非公開開催','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('クローズド','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('クローズド開催','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('身内限定','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('身内のみ','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('仲間内限定','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('仲間内のみ','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('知り合い限定','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('知人限定','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('友人限定','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('友達限定','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('関係者のみ','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('関係者限定','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('メンバー限定','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('招待者限定','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('招待制','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('内輪限定','private_limited',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('こっそり','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('こっそり開催','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('ひっそり','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('ひっそり開催','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('秘密開催','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('シークレット','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('シークレット開催','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('裏開催','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('裏ミートアップ','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('裏Meetup','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('内緒開催','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('非告知','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('非告知開催','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('限定公開','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('隠れ開催','secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('主催者不在','host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('主催不在','host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('主催者はいません','host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('主催者はいない','host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('主催者は来ません','host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('主催は来ません','host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('主催者は現地にいません','host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('主催者は現地不在','host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('主催なし','host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('スタッフ不在','host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('運営不在','host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('現地スタッフ不在','host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('現地集合不要','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('集合不要','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('現地に来なくてOK','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('来なくてOK','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('来場不要','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('参加不要','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('現地参加不要','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('現地に来る必要なし','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('現地に来る必要はありません','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('来場しなくてOK','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('顔出し不要','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('対面不要','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('非対面','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('現地にいなくてもOK','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('その場にいなくてもOK','non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインだけ','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインのみ','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインだけでOK','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインのみでOK','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインだけでもOK','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインのみでもOK','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインして終わり','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインしたら終了','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインして解散','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックイン後解散','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインだけ参加','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインのみ参加','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインだけお願いします','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインのみお願いします','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインだけ可能','checkin_only',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('フリーチェックイン','free_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('自由チェックイン','free_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('いつでもチェックイン','free_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('好きな時間にチェックイン','free_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('確認なしでチェックイン','free_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックイン確認なし','free_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックイン自由','free_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックイン開放','free_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックイン開放中','free_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('無条件チェックイン','free_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('誰でもチェックイン','free_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックインご自由に','free_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('報酬だけ','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('報酬のみ','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('報酬目的','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('報酬回収','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('報酬受取','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('リワードだけ','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('リワードのみ','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('リワード目的','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('リワード回収','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('リワード受取','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('特典だけ','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('特典のみ','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('特典目的','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('特典回収','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('アイテム回収','reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('一般募集なし','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('一般募集しません','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('一般公開なし','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('一般公開しません','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('新規参加不可','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('新規お断り','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('初参加不可','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('初参加お断り','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('外部参加不可','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('外部の方お断り','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('飛び入り不可','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('飛び入りお断り','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('事前承認制','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('承認者のみ','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('指定メンバーのみ','participation_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('短時間開催','short_quick',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('短時間ミートアップ','short_quick',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('短時間Meetup','short_quick',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('すぐ解散','short_quick',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('即解散','short_quick',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('チェックイン後すぐ解散','short_quick',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('短時間で終了','short_quick',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('すぐ終わります','short_quick',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('数分だけ','short_quick',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('数分開催','short_quick',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('private meetup','english_private',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('private event','english_private',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('members only','english_private',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('invite only','english_private',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('invited only','english_private',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('closed meetup','english_private',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('closed event','english_private',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('secret meetup','english_secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('secret event','english_secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('hidden meetup','english_secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('unlisted meetup','english_secret',3,'TITLE_STRONG',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('host absent','english_host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('host will not attend','english_host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('host not present','english_host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('no host','english_host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('staff absent','english_host_absent',4,'HOST_ABSENT_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('no need to attend','english_non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('no need to come','english_non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('attendance not required','english_non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('in-person not required','english_non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('remote only','english_non_attendance',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('check-in only','english_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('check in only','english_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('just check in','english_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('check-in and leave','english_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('free check-in','english_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('free check in','english_checkin',4,'FREE_CHECKIN_TEXT',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('reward only','english_reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('rewards only','english_reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('reward pickup','english_reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('claim reward','english_reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('rewards pickup','english_reward',3,'TITLE_REWARD',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('no public participation','english_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('no walk-ins','english_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('registered members only','english_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1),
('approved members only','english_limit',2,'TITLE_CAUTION',false,'(?:ではありません|ではない|禁止|不可|NG|ＮＧ|お断り|しません|しない|ではございません|やめてください|not\\s+|no\\s+|prohibited|forbidden|do\\s+not|don''t|isn''t|is\\s+not)',true,1)
on conflict (lower(phrase),category) do nothing;
